#!/usr/bin/env bash

# innstalling nginx and adding content to the default page
sudo apt update
sudo apt-get -y install nginx

sudo mkdir -p /etc/nginx/html
sudo touch /etc/nginx/html/index.html
sudo chown -R "$USER:$USER" /etc/nginx/html
sudo chmod -R 755 /etc/nginx/html

# adding content to root page
echo "Hello World!" | sudo tee  /etc/nginx/html/index.html

# consfigure the server
sudo printf %s " server {
	listen      80 default_server;
	listen      [::]:80 default_server;
	root        /etc/nginx/html;
	index       index.html index.htm;
}" | sudo tee /etc/nginx/sites-available/default

sudo service nginx restart 
