#!/usr/bin/env bash
# Installs Nginx 
# set the default to hello world

apt-get update
apt-get install -y nginx

mkdir /etc/nginx/html
touch /etc/nginx/html/index.html

# adding content
echo "Hello World!" > /etc/nginx/html/index.html

# setting to listen to port 80
printf %s "server {
     listen      80 default_server;
     listen      [::]:80 default_server;
     root        /etc/nginx/html;
     index       index.html index.htm;

     location /redirect_me {
	return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;

}
}
" > /etc/nginx/sites-available/default


service nginx restart 
