#!/usr/bin/env bash
# Installs Nginx 
# set the default to hello world

apt-get update
apt-get install -y nginx

mkdir -p  /var/www/html
touch  /var/www/html/index.html
touch  /var/www/html/custom_404.html

# adding content
echo "Hello World!" > /var/www/html/index.html
echo "Ceci n'est pas une page" > /var/www/html/custom_404.html

# setting to listen to port 80
printf %s "server {
    listen 80 default_server;
    listen [::]:80 default_server;
    add_header X-Served-By $HOSTNAME;
    root   /var/www/html;
    index  index.html index.htm;

    location /redirect_me {
        return 301 http://cuberule.com/;
    }

    error_page 404 /custom_404.html;
    location /404 {
      root /var/www/html;
      internal;
    }
}
" > /etc/nginx/sites-available/default
