#!/usr/bin/env bash
# Automatizing the nginx configuration
sudo apt-get -y update
sudo apt-get -y install nginx
sudo sed -i "6i \\\tadd_header X-Served-By $HOSTNAME;" /etc/nginx/sites-available/default
sudo service nginx restart
