#!/usr/bin/env bash
# this script installs ha proxy on a server that willl act a load balancer

sudo apt-get -y update
sudo apt-get -y install haproxy

echo "ENABLED=1" >> /etc/default/haproxy
sudo cp -a /etc/haproxy/haproxy.cfg{,.original_copy}
touch /etc/haproxy/haproxy.cf

# adding configuration
printf %s "

frontend myfrontend
        bind *:80
        mode http
        default_backend myBackend

backend myBackend
        balance roundrobin
        server 270520-web-01 54.89.179.242:80 check
        server 270520-web-02 3.90.83.124:80 check " >> /etc/haproxy/haproxy.cfg

sudo service haproxy restart
