#!/usr/bin/env bash
# this script installs ha proxy on a server that willl act a load balancer

apt-get install --no-install-recommends software-properties-common
add-apt-repository ppa:vbernat/haproxy-2.0
apt-get install haproxy=2.0.\*

echo "ENABLED=1" >> /etc/default/haproxy
sudo cp -a /etc/haproxy/haproxy.cfg{,.original_copy}
touch /etc/haproxy/haproxy.cf

# adding configuration
printf %s "

frontend myfrontend
        bind *:80
        mode http
        default_backend myBackend

backend myBackend
        balance roundrobin
        server 270520-web-01 54.89.179.242:80 check
        server 270520-web-02 3.90.83.124:80 check " >> /etc/haproxy/haproxy.cfg

sudo service haproxy restart
