#!/usr/bin/env bash
# this script installs ha proxy on a server that willl act a load balancer

sudo apt-get update
sudo apt-get install haproxy

# adding configuration
printf %s '
defaults
	mode http
	timeout client 10s
	timeout connect 5s
	timeout server 10s 
	timeout http-request 10s

frontend myfrontend
	bind *:80
	mode http
	default_backend myBackend

backend myBackend
	balance roundrobin
	server 270520-web-01 54.89.179.242:80 check
	server 270520-web-02 3.90.83.124:80 check '
> /etc/haproxy/haproxy.cfg

# enable the script to be stated by init script
echo "ENABLED=1" | sudo tee -a /etc/default/haproxy

sudo service haproxy restart
