#!/usr/bin/env bash
# this a backup file for the database

# backing up all databases
mysqldump -u root -p "$1" --all-databases > backup.sql

# create an archive
tar -cvzf "$(date +%d-%m-%Y)".tar.gz  backup.sql
