#!/usr/bin/env bash
# this a backup file for the database

# backing up all databases
mysqldump -u root -p "$1" --all-databases > backup.sql
day=$(date +%d)
month=$(date +%m)
year=$(date +%Y)

# create an archive
tar -czf "$day-$month-$year".tar.gz  backup.sql
