#!/usr/bin/env bash
# Bash script that displays the content of the file /etc/passwd.

file="/etc/passwd"
while read -r line
do
	username=$(echo "$line" | cut -d ":" -f 1)
	userid=$(echo "$line" | cut -d ":" -f 3)
	home=$(echo "$line" | cut -d ":" -f 6)
	echo "$username:$userid:$home"
done < $file
