#!/usr/bin/env bash
#configures an Ubuntu server to change the host file

cp /etc/hosts ~/hosts.new
sed -ie 's/127.0.0.1/127.0.0.2/' ~/hosts.new

#search if facebook is not present
if ! grep -q facebook.com ~/hosts.new
then
	echo "8.8.8.8	facebook.com" >> ~/hosts.new
else
	sed -ie 's/.*facebook\.com/8.8.8.8   facebook.com/' ~/hosts.new
fi
cp -f ~/hosts.new /etc/hosts
